const logic = module.exports

//Discord emojis
logic.emojis = {
  chests: {
    'Silver Chest': '<:silverchest:324531061696495616>',
    'Golden Chest': '<:goldchest:324531061801484290>',
    'Giant Chest': '<:giantchest:324531062082633730>',
    'Magical Chest': '<:magicalchest:324531062116057089> ',
    'Epic Chest': '<:epicchest:324531062816636928>',
    'Legendary Chest': '<:legendarychest:324531062858579968>',
    'Super Magical Chest': '<:supermagicalchest:324531062350807040>',
  },
  wifi: '<:wifi:313982284661391361>',
  cards: {},
}

//Tag Verification
logic.tag_characters = '0289PYLQGRJCUV'

//Clash Royale in-game hints
logic.hints = [
  "Elixir generates automatically during battle. Playing a card costs Elixir.",
  "Save your Elixir to play multiple cards at once.",
  "Play multiple cards together to create a stronger push.",
  "Your experience level indicates the strength of your King and Crown Towers.",
  "Gain experience by upgrading your cards.",
  "Big troops are vulnerable to groups of small troops.",
  "Groups of small troops are vulnerable to area damage.",
  "Join a Clan and receive 100 Gems for completing the achievement.",
  "TV Royale contains some of the best games played recently. Watch and learn!",
  "Use Arrows to stop a group of small troops.",
  "Giants target buildings and ignore enemy troops.",
  "The Knight followed by Archers is a simple and effective strategy.",
  "Some troops deal area damage, hitting multiple units at once.",
  "You get one Free Chest every four hours. You can store two of them.",
  "Each battle can last three minutes, possibly extended by a minute of sudden death tiebreaker.",
  "During sudden death, the first player to get a Crown wins.",
  "There are three types of card: Troops, Buildings and Spells.",
  "Cards come in four levels of rarity: Common, Rare, Epic and Legendary.",
  "Balance your Battle Deck with cards that can target both ground and air.",
  "You can take eight cards from your collection into battle. This is your Battle Deck.",
  "Complete achievements to earn Gems!",
  "Donating cards to your Clan gives experience and Gold, and makes you feel all warm and fuzzy inside.",
  "The King only joins the fight after taking damage or losing a Crown Tower.",
  "The Princesses protect the King from atop their Crown Towers.",
  "Goblins only joined the Arena after their union signed a lucrative contract with the Royales.",
  "All buildings slowly lose hitpoints, expiring after a set amount of time.",
  "All Crown Towers target both ground and air troops.",
  "Some defensive buildings only target ground troops, while others target both ground and air.",
  "Common Cards can be upgraded to level 13.",
  "Rare Cards can be upgraded to level 11.",
  "Epic Cards can be upgraded to level 8.",
  "Upgrading cards makes them more powerful, but their Elixir cost remains the same.",
  "Gain Trophies to access new Arenas, which unlock more cards.",
  "The selection of cards available in the Shop refreshes every 24 hours.",
  "Rarer chests contain more cards and Gold.",
  "Higher Arena chests contain more cards and Gold.",
  "Gold Chests always contain at least one Rare Card.",
  "Magical Chests always contain at least one Epic Card.",
  "Your opponents are selected based on your Trophy count.",
  "Bomb Towers are good against groups of small troops.",
  "Support durable troops by deploying ranged troops behind them.",
  "Protect squishy troops by deploying durable troops in front of them.",
  "Prince deals double damage to the first target he strikes while charging.",
  "Tesla cannot be damaged while underground, and only pops up when enemy troops are in range.",
  "You can deploy on your opponent's side of the Arena after destroying one of their Crown Towers.",
  "Use taunts to show your opponent you're a good sport. Or not.",
  "Sometimes it's worth pushing for a three-Crown victory. Sometimes securing two Crowns is the smarter play.",
  "The Balloon drops a bomb when destroyed. Don't stand still.",
  "Elixir production is doubled during the final 60 seconds.",
  "The Goblin Hut and Barbarian Hut spawn troops periodically.",
  "The Tombstone releases a group of Skeletons when destroyed.",
  "The Rage Spell increases movement and attack speed.",
  "Damage spells like the Fireball deal half damage to Crown Towers.",
  "10 Elixir is the maximum you can hold.",
  "During battle, your starting cards are randomly selected from your Battle Deck.",
  "Every 24 hours you can collect 10 Crowns to unlock the Crown Chest.",
  "Lure troops to your side of the Arena to engage them with your Crown Towers.",
  "Using Elixir efficiently is the key to victory.",
  "X-Bows and Mortars can directly damage your opponent's Crown Towers if positioned near the middle.",
  "Giants can be effective on defense, too.",
  "Sometimes holding on to a card is the best play to make.",
  "When deployed, all troops march towards the enemy King, attacking their preferred targets along the way.",
  "The Inferno Tower's damage increases over time while attacking the same target.",
  "The Giant Skeleton carries a large bomb, which he carelessly drops when destroyed. Oops!",
  "Each Sunday the Shop contains twice as many cards!",
  "Free Chests and Crown Chests are the only chests which can contain Gems.",
  "Hog Riders can jump over the river.",
  "Golems target buildings and ignore troops.",
  "The Golem explodes when destroyed and splits into two smaller Golemites.",
  "Golem has a heart made of stone.",
  "The P.E.K.K.A and Mini P.E.K.K.A are easily distracted, but they hit like a truck.",
  "P.E.K.K.A: No-one knows what's behind that mask. Maybe even another mask.",
  "Trophies that you win are deducted from your opponent's Trophies!",
  "Experts have long believed that lightning is attracted to tall objects, however, new research indicates that lightning is, in fact, attracted to high hitpoints.",
  "One day, Wall Breakers realized that they could do a lot more damage if they THREW the bomb instead of sat beside it. Imagine that...",
  "The Wizard can control all elements, except his hair."
]
